#!/usr/bin/env node
// Post-build step: wrap the Astro Cloudflare adapter's generated Worker entry
// with HTTP Basic Auth.
//
// WHY: The @astrojs/cloudflare adapter's handler short-circuits prerendered
// pages by returning env.ASSETS.fetch() BEFORE app.render() is called. Astro
// middleware only runs inside app.render(), so it never executes for
// prerendered HTML. This wrapper intercepts ALL requests at the Worker level
// — before the adapter's asset check — so auth protects every page.
//
// Auth is OPT-IN: if AUTH_USER / AUTH_PASS are unset or empty, the wrapper is
// a pass-through and the Worker behaves exactly as the adapter generated it.

import { rename, writeFile } from "node:fs/promises";
import { join } from "node:path";

const SERVER_DIR = new URL("../dist/server/", import.meta.url).pathname;

// 1. Rename the generated entry so we can import it from the wrapper.
const generatedEntry = join(SERVER_DIR, "entry.mjs");
const renamedEntry = join(SERVER_DIR, "astro-entry.mjs");

try {
  await rename(generatedEntry, renamedEntry);
} catch {
  // Already wrapped (idempotent) — nothing to do.
  process.exit(0);
}

// 2. Write the auth wrapper as the new entry.mjs.
const wrapper = `// AUTO-GENERATED by scripts/wrap-worker.mjs — do not edit.
// Wraps the Astro Cloudflare adapter's handler with HTTP Basic Auth.
globalThis.process ??= {};
globalThis.process.env ??= {};
import "cloudflare:workers";
import { default as astroHandler } from "./astro-entry.mjs";

function basicAuthGate(authUser, authPass, authorization, realm) {
  realm = realm || "draestelamas";
  if (!authUser || !authPass) return null;
  if (!authorization || !authorization.startsWith("Basic ")) {
    return unauthorizedResponse(realm);
  }
  var encoded = authorization.slice("Basic ".length).trim();
  var decoded;
  try {
    decoded = atob(encoded);
  } catch {
    return unauthorizedResponse(realm);
  }
  var colonIdx = decoded.indexOf(":");
  if (colonIdx === -1) return unauthorizedResponse(realm);
  var user = decoded.slice(0, colonIdx);
  var pass = decoded.slice(colonIdx + 1);
  if (constantTimeEqual(user, authUser) && constantTimeEqual(pass, authPass)) {
    return null;
  }
  return unauthorizedResponse(realm);
}

function constantTimeEqual(a, b) {
  if (a.length !== b.length) return false;
  var mismatch = 0;
  for (var i = 0; i < a.length; i++) {
    mismatch |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return mismatch === 0;
}

function unauthorizedResponse(realm) {
  return new Response("401 Unauthorized\\n", {
    status: 401,
    headers: {
      "WWW-Authenticate": 'Basic realm="' + realm + '", charset="UTF-8"',
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}

var handler = {
  fetch: async function (request, env, ctx) {
    var gate = basicAuthGate(
      env.AUTH_USER,
      env.AUTH_PASS,
      request.headers.get("authorization"),
    );
    if (gate) return gate;

    var response = await astroHandler.fetch(request, env, ctx);

    // When auth is active, prevent the edge cache from storing auth-gated
    // responses — otherwise an unauthenticated request could receive a
    // cached page that was fetched with valid credentials.
    if (env.AUTH_USER && env.AUTH_PASS) {
      var headers = new Headers(response.headers);
      headers.set("Cache-Control", "no-store, s-maxage=0");
      return new Response(response.body, {
        status: response.status,
        statusText: response.statusText,
        headers: headers,
      });
    }

    return response;
  },
};

export { handler as default };
`;

await writeFile(generatedEntry, wrapper, "utf8");

// 3. Update wrangler.json to keep main pointing at entry.mjs (it already does,
//    but make sure no_bundle is preserved so wrangler doesn't re-bundle and
//    tree-shake the wrapper). No change needed — main is already "entry.mjs".

console.log("✓ Wrapped Worker entry with Basic Auth gate");
